Repository crazycodigo/Coding-Basics-HacktoberFest2022, pull requests merged in 2022-10, with the labels that each got.

#6 Added Whack-Mole-Game in JavaScript
  Whack-a-mole-game/index.html
  Whack-a-mole-game/mole.jpg
  Whack-a-mole-game/script.js
  Whack-a-mole-game/style.css
Labels: hacktoberfest

#5 Added cpp LeetCode Questions
  LeetCode Questions/C++/1. Problems/48-rotateImage.cpp
  LeetCode Questions/C++/1. Problems/74-searchA2DMatrix.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/48-rotateImage.png
  LeetCode Questions/C++/2. Accepted Screenshots/74-searchA2DMatrix.png
Labels: hacktoberfest

#8 232-queue-using-stacks.cpp
  LeetCode Questions/C++/1. Problems/232-queue-using-stacks.cpp
Labels: hacktoberfest

#9 Added leetcode solution for 17. Letter Combinations of A Phone in Jav…
  LeetCode Questions/Javascript/1. Problems/17-letterCombinationsOfAPhoneNumber.js
  LeetCode Questions/Javascript/2. Accepted Screenshots/17-letterCombinationsOfAPhoneNumber.png
Labels: hacktoberfest

#10 Update contribution guidelines
  CONTRIBUTING.md
Labels: hacktoberfest

#13 Solved reverseInteger Question in LeetCode
  LeetCode Questions/C++/1. Problems/reverseInteger.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/reverseInteger.png
Labels: hacktoberfest

#12 Adding polyfills for Higher Order Functions in javascript - map(), filter() and reduce()
  Javascript Polyfills/customFilter.js
  Javascript Polyfills/customMap.js
  Javascript Polyfills/customReduce.js
Labels: hacktoberfest

#16 LC-990 Solution
  LeetCode Questions/C++/1. Problems/990-SatisfiabilityOfEqualityEquations.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/990-SatisfiabilityOfEqualityEquations.png
Labels: hacktoberfest

#20 basic program to create TicTacToe in C
  TicTacToe in C
Labels: hacktoberfest-accepted

#17 Added an AIML Project using python
  AI Projects/AI Car Detector/Self_Driving_Car.py
  AI Projects/AI Car Detector/assets/car1.avi
  AI Projects/AI Car Detector/assets/car2.avi
  AI Projects/AI Car Detector/assets/haar_features.png
  AI Projects/AI Car Detector/bike.xml
  AI Projects/AI Car Detector/bus.xml
  AI Projects/AI Car Detector/cars.xml
  AI Projects/AI Car Detector/pedestrian.xml
Labels: hacktoberfest-accepted

#14 Added 4 new leetcode Medium Question C++
  LeetCode Questions/C++/1. Problems/13-roman-to-integer.cpp
  LeetCode Questions/C++/1. Problems/658-find-k-closest-elements.cpp
  LeetCode Questions/C++/1. Problems/66-plus-one.cpp
  LeetCode Questions/C++/1. Problems/75-sort-colors.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/13-roman-to-integer.png
  LeetCode Questions/C++/2. Accepted Screenshots/658-find-k-closest-elements.png
  LeetCode Questions/C++/2. Accepted Screenshots/66-plus-one.png
  LeetCode Questions/C++/2. Accepted Screenshots/75-sort-colors.png
Labels: hacktoberfest-accepted

#23 Added AI Face detector code
  AI Projects/Smile Detector/README.md
  AI Projects/Smile Detector/face.xml
  AI Projects/Smile Detector/smile.py
  AI Projects/Smile Detector/smile.xml
Labels: hacktoberfest-accepted

#27 Added Spock Lizard Rock Paper Scissor Game using JS
  Spock Rock Game/confetti.js
  Spock Rock Game/index.html
  Spock Rock Game/script.js
  Spock Rock Game/style.css
Labels: hacktoberfest-accepted

#28 Implemented Singly Linked List in Java.
  .DS_Store
  Data Structure Implementations/LinkedList.java
Labels: hacktoberfest-accepted

#33 Create Rock paper scissors game.py
  Rock paper scissors game.py
Labels: hacktoberfest-accepted

#35 React application to tell Hot or Cold Season based on Geo Location
  Cold-Hot React/.gitignore
  Cold-Hot React/README.md
  Cold-Hot React/package-lock.json
  Cold-Hot React/package.json
  Cold-Hot React/public/favicon.ico
  Cold-Hot React/public/index.html
  Cold-Hot React/public/logo192.png
  Cold-Hot React/public/logo512.png
  Cold-Hot React/public/manifest.json
  Cold-Hot React/public/robots.txt
  Cold-Hot React/src/SeasonDisplay.css
  Cold-Hot React/src/SeasonDisplay.js
  Cold-Hot React/src/Spinner.js
  Cold-Hot React/src/index.js
Labels: hacktoberfest-accepted

#38 Created a HTML, CSS Navbar
  Navbar-html-css/index.html
  Navbar-html-css/style.css
Labels: good first issue, hacktoberfest-accepted

#43 Added Real-time face detection
  AI Projects/Real-time face detector/FaceDetector.py
  AI Projects/Real-time face detector/README.md
  AI Projects/Real-time face detector/haarcascade_frontalface_default.xml
Labels: hacktoberfest-accepted

#44 Digital Clock Using HTML, CSS, JavaScript (With Screen shot added)
  Digital_clock_using_JavaScript/index.html
  Digital_clock_using_JavaScript/screenShot.PNG
  Digital_clock_using_JavaScript/script.js
  Digital_clock_using_JavaScript/style.css
Labels: hacktoberfest-accepted

#46 twoSum code added
  LeetCode Questions/C++/1. Problems/1-twoSum.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/1-twoSum.png
Labels: hacktoberfest-accepted

#48 clock-javscript
  clock-javascript/Screenshot (633).png
  clock-javascript/clock.html
  clock-javascript/clock.js
Labels: hacktoberfest-accepted

#47 Added the ss as well as program file for RemoveNthNodeFromEndOfLinkedList question on leetcode
  LeetCode Questions/C++/1. Problems/remove_nth_node_from_end_of_ll.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/remove-nth-node-from-end-of-linked-list.png
Labels: hacktoberfest-accepted

#50 added new counter project
  Counter JavaScript/Readme.md
  Counter JavaScript/app.js
  Counter JavaScript/index.html
  Counter JavaScript/styles.css
Labels: hacktoberfest-accepted

#61 added animations
  Cold-Hot React/src/SeasonDisplay.css
  Cold-Hot React/src/SeasonDisplay.js
Labels: hacktoberfest-accepted

#64 Add HTML+CSS game similar to Google T-rex
  Keto Mario/assets/cactus.png
  Keto Mario/assets/mario.png
  Keto Mario/assets/stars.png
  Keto Mario/index.html
  Keto Mario/style.css
Labels: hacktoberfest-accepted

#52 Stickman game in Python
  Python Games/stickman_game.py
Labels: hacktoberfest-accepted

#30 Added Singly Linked list all Operations in cpp
  linked_list_implementation cpp/linked_list_practice.cpp
  linked_list_practice.cpp
Labels: hacktoberfest-accepted

#78 Accordion JS - Hacktoberfest
  Accordion-Fest2022/index.html
  Accordion-Fest2022/script.js
  Accordion-Fest2022/style.css
Labels: hacktoberfest-accepted

#49 Add luis contribution
  Typewritter/index.html
  Typewritter/main.css
  Typewritter/writter.js
Labels: hacktoberfest-accepted

#79 added a leetcode problem number "120" (traingle)
  LeetCode Questions/Java/Traingle.java
Labels: hacktoberfest-accepted

#53 Added LeetCode Questions
  LeetCode Questions/C++/1. Problems/121-best-time-to-buy-and-sell-stock.cpp
  LeetCode Questions/C++/1. Problems/169-majority-element.cpp
  LeetCode Questions/C++/1. Problems/344-reverse-string.cpp
  LeetCode Questions/C++/1. Problems/560-subarray-sum-equals-k.cpp
  LeetCode Questions/C++/1. Problems/918-maximum-sum-circular-subarray.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/121-best-time-to-buy-and-sell-stock.PNG
  LeetCode Questions/C++/2. Accepted Screenshots/169-majority-element.PNG
  LeetCode Questions/C++/2. Accepted Screenshots/344-reverse-string.PNG
  LeetCode Questions/C++/2. Accepted Screenshots/560-subarray-sum-equals-k.PNG
  LeetCode Questions/C++/2. Accepted Screenshots/918-maximum-sum-circular-subarray.PNG
Labels: hacktoberfest-accepted

#80 Snake game Added
  Python Games/snake.py
Labels: hacktoberfest-accepted

#75 Combination Sum Leetcode problem
  LeetCode Questions/C++/CombinationSum.cpp
  LeetCode Questions/C++/pic1.png
Labels: hacktoberfest-accepted

#74 Added Mine Sweeper Game
  Python Games/MineSweeper/MineSweeper.py
  Python Games/MineSweeper/__pycache__/cell.cpython-310.pyc
  Python Games/MineSweeper/__pycache__/settings.cpython-310.pyc
  Python Games/MineSweeper/__pycache__/utils.cpython-310.pyc
  Python Games/MineSweeper/cell.py
  Python Games/MineSweeper/settings.py
  Python Games/MineSweeper/utils.py
Labels: hacktoberfest-accepted

#71 Created Responsive Navbar
  Navbar-html-css/ResponsiveNavbar.html
Labels: hacktoberfest-accepted

#66 Added Drowsiness Detector in AI Projects
  AI Projects/Drowsiness Detector/README.md
  AI Projects/Drowsiness Detector/alarm.wav
  AI Projects/Drowsiness Detector/main.py
  AI Projects/Drowsiness Detector/requirements.txt
Labels: hacktoberfest-accepted

#69 added a new leetcode solution
  LeetCode Questions/C++/1. Problems/Minimum Moves to Equal Array Elements.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/Screenshot (130).png
Labels: hacktoberfest-accepted

#82 added new file containing resourses
  cs-resources/README.md
Labels: good first issue, hacktoberfest-accepted

#59 Leetcode hard
  LeetCode Questions/C++/1. Problems/1074. Number of Submatrices That Sum to Target.cpp
  LeetCode Questions/C++/1. Problems/1354. Construct Target Array With Multiple Sums.cpp
  LeetCode Questions/C++/1. Problems/315. Count of Smaller Numbers After Self.cpp
  LeetCode Questions/C++/1. Problems/42. Trapping Rain Water.cpp
  LeetCode Questions/C++/1. Problems/968. Binary Tree Cameras.cpp
  LeetCode Questions/C++/1. Problems/987. Vertical Order Traversal of a Binary Tree.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/1074. Number of Submatrices That Sum to Target.png
  LeetCode Questions/C++/2. Accepted Screenshots/1354. Construct Target Array With Multiple Sums.png
  LeetCode Questions/C++/2. Accepted Screenshots/315. Count of Smaller Numbers After Self.png
  LeetCode Questions/C++/2. Accepted Screenshots/42. Trapping Rain Water.png
  LeetCode Questions/C++/2. Accepted Screenshots/968. Binary Tree Cameras.png
  LeetCode Questions/C++/2. Accepted Screenshots/987. Vertical Order Traversal of a Binary Tree.png
Labels: hacktoberfest-accepted

#58 Leetcode 1
  LeetCode Questions/C++/1. Problems/2070 Most Beautiful Item For Each Query.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/2070 Most Beautiful Item For Each Query.png
Labels: hacktoberfest-accepted

#60 Create MergeSort.java
  Algoritms/MergeSort.java
Labels: hacktoberfest-accepted

#84 Added basic/beginner projects with python
  Python Basic Projects/Billing System/about.md
  Python Basic Projects/Billing System/billing_system.py
  Python Basic Projects/Calender with GUI/about.md
  Python Basic Projects/Calender with GUI/calender.py
  Python Basic Projects/Download Instagram pfp/about.md
  Python Basic Projects/Download Instagram pfp/insta_pfp.py
  Python Basic Projects/Guess the Number/about.md
  Python Basic Projects/Guess the Number/guess.py
  Python Basic Projects/Hangman/__pycache__/hangman_visuals.cpython-39.pyc
  Python Basic Projects/Hangman/__pycache__/words.cpython-39.pyc
  Python Basic Projects/Hangman/hangman.py
  Python Basic Projects/Hangman/hangman_visuals.py
  Python Basic Projects/Hangman/words.py
  Python Basic Projects/Library mangement/about.md
  Python Basic Projects/Library mangement/librabry_management.py
  Python Basic Projects/Listen news/about.md
  Python Basic Projects/Listen news/listen_news.py
  Python Basic Projects/Login/about.md
  Python Basic Projects/Login/login.py
  Python Basic Projects/Password Generator/about.md
  Python Basic Projects/Password Generator/password.py
  Python Basic Projects/Password Generator/password2.py
  Python Basic Projects/Rock, Paper, Scissors/about.md
  Python Basic Projects/Rock, Paper, Scissors/rock_paper_scissors.py
  Python Basic Projects/Snake, Water, Gun/about.md
  Python Basic Projects/Snake, Water, Gun/snake_water_gun.py
  Python Basic Projects/Tip Calculator/about.md
  Python Basic Projects/Tip Calculator/tipcalc.py
  Python Basic Projects/Treasure Island/about.md
  Python Basic Projects/Treasure Island/treasure_island.py
  Python Basic Projects/URL Shortner/about.md
  Python Basic Projects/URL Shortner/shortner.py
  Python Basic Projects/Weight Converter GUI/about.md
  Python Basic Projects/Weight Converter GUI/weight_converter.py
  Python Basic Projects/Youtube download/about.md
  Python Basic Projects/Youtube download/yt_download.py
Labels: hacktoberfest-accepted

#87 Added game of Cross and Zeroes in C
  Tic Tac Toe/a.exe
  Tic Tac Toe/game.c
  Tic Tac Toe/leaderboards_name.txt
  Tic Tac Toe/leaderboards_points.txt
Labels: hacktoberfest-accepted

#113 Leetcode set
  LeetCode Questions/C++/1. Problems/2280. Minimum Lines to Represent a Line Chart.cpp
  LeetCode Questions/C++/1. Problems/2300. Successful Pairs of Spells and Potions.cpp
  LeetCode Questions/C++/1. Problems/2429. Minimize XOR.cpp
  LeetCode Questions/C++/1. Problems/3. Longest Substring Without Repeating Characters.cpp
  LeetCode Questions/C++/1. Problems/33. Search in Rotated Sorted Array.cpp
  LeetCode Questions/C++/1. Problems/665. Non-decreasing Array.cpp
  LeetCode Questions/C++/1. Problems/91. Decode Ways.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/2280. Minimum Lines to Represent a Line Chart.png
  LeetCode Questions/C++/2. Accepted Screenshots/2300. Successful Pairs of Spells and Potions.png
  LeetCode Questions/C++/2. Accepted Screenshots/2429. Minimize XOR.png
  LeetCode Questions/C++/2. Accepted Screenshots/3. Longest Substring Without Repeating Characters.png
  LeetCode Questions/C++/2. Accepted Screenshots/33. Search in Rotated Sorted Array.png
  LeetCode Questions/C++/2. Accepted Screenshots/665. Non-decreasing Array.png
  LeetCode Questions/C++/2. Accepted Screenshots/91. Decode Ways.png
Labels: hacktoberfest-accepted

#111 Valid Parentheses Python code
  LeetCode Questions/Python/1.Problems/valid_parentheses.py
  LeetCode Questions/Python/2.Accepted Screenshots/valid_parentheses.png
Labels: hacktoberfest-accepted

#117 add tictactoegame project
  TicTacToeGame/index.html
  TicTacToeGame/script.js
  TicTacToeGame/style.css
Labels: hacktoberfest-accepted

#110 added quiz site
  Quiz Site/index.html
  Quiz Site/script.js
  Quiz Site/style.css
Labels: hacktoberfest-accepted

#112 LeetCode med
  LeetCode Questions/C++/1. Problems/300. Longest Increasing Subsequence.cpp
  LeetCode Questions/C++/1. Problems/307. Range Sum Query - Mutable.cpp
  LeetCode Questions/C++/1. Problems/376. Wiggle Subsequence.cpp
  LeetCode Questions/C++/1. Problems/378. Kth Smallest Element in a Sorted Matrix.cpp
  LeetCode Questions/C++/1. Problems/394. Decode String.cpp
  LeetCode Questions/C++/2. Accepted Screenshots/300. Longest Increasing Subsequence.png
  LeetCode Questions/C++/2. Accepted Screenshots/307. Range Sum Query - Mutable.png
  LeetCode Questions/C++/2. Accepted Screenshots/376. Wiggle Subsequence.png
  LeetCode Questions/C++/2. Accepted Screenshots/378. Kth Smallest Element in a Sorted Matrix.png
  LeetCode Questions/C++/2. Accepted Screenshots/394. Decode String.png
Labels: hacktoberfest-accepted

#85 Printing LCS
  Algoritms/Printing LCS
Labels: hacktoberfest-accepted

#109 Create quickSort.java
  Algoritms/quickSort.java
Labels: hacktoberfest-accepted

#108 added terminal commands
  cs-resources/README.md
Labels: hacktoberfest-accepted

#106 Path Sum of tree in java
  Algoritms/Path Sum.java
Labels: hacktoberfest-accepted

#103 stack operation
  Stack_operations_using_C/stack_operations_practice.c
  Stack_operations_using_C/stack_operations_practice.exe
Labels: hacktoberfest-accepted

#130 Remove Element From List
  LeetCode Questions/Python/1.Problems/remove_element.py
  LeetCode Questions/Python/2.Accepted Screenshots/remove_element.jpg
Labels: hacktoberfest-accepted

#129 Add sudoku_solver.cpp
  sudoku_solver-main/README.md
  sudoku_solver-main/Screenshot (3).png
  sudoku_solver-main/main.cpp
  sudoku_solver-main/sample1.txt
Labels: hacktoberfest-accepted

#98 Colorful Sketch Hoverboard.
  Hoverboard Colorful/app.js
  Hoverboard Colorful/index.html
  Hoverboard Colorful/style.css
Labels: hacktoberfest-accepted

#126 Added Linear Regression Code
  ML Algorithms/Linear_Regression.ipynb
Labels: hacktoberfest-accepted

#133 Create Floyd Warshall.cpp
  Algoritms/Floyd Warshall.cpp
Labels: hacktoberfest-accepted

#136 The robot dance page
  Robot_game/index.html
  Robot_game/robot.css
Labels: hacktoberfest-accepted

#121 Best Time to Buy and Sell Stock
  Algoritms/QuickSort.java
  LeetCode Questions/Java/Best_Time_To_Buy_and_Sell_Stock.java
Labels: hacktoberfest-accepted, spam

#96 Added solution of two sum problem in python.
  LeetCode Questions/Python/1. Problems/1_two_sum.py
  LeetCode Questions/Python/2. Accepted Screenshots/1_two_sum.png
Labels: hacktoberfest-accepted

#92 Flipkart clone added
  FLIPKART CLONE/css/responsive.css
  FLIPKART CLONE/css/style.css
  FLIPKART CLONE/css/utils.css
  FLIPKART CLONE/index.html
  FLIPKART CLONE/logo.png
Labels: hacktoberfest-accepted

#89 Added Problem Number 202 In LeetCode
  LeetCode Questions/Java/HappyNumber.java
Labels: hacktoberfest-accepted

#54 Create customStack
  LeetCode Questions/Java/customStack
Labels: hacktoberfest-accepted
